import type { DietaryTag, ProductPresentationModel, ProductStockStatus } from './product.types';

export const productCategories = [
  { id: 'plant-milk', name: 'Sữa hạt' },
  { id: 'yogurt', name: 'Sữa chua' },
  { id: 'healthy-drinks', name: 'Đồ uống healthy' },
  { id: 'whole-grains', name: 'Granola & ngũ cốc' },
  { id: 'healthy-snacks', name: 'Snack healthy' },
  { id: 'ready-meals', name: 'Salad & bữa ăn' },
  { id: 'high-protein', name: 'Thực phẩm giàu protein' },
  { id: 'low-sugar', name: 'Thực phẩm ít đường' },
] as const;

export const productBrands = [
  { id: 'healthyhub-select', name: 'HealthyHub Select' },
  { id: 'moc-nhien', name: 'Mộc Nhiên' },
  { id: 'green-farm', name: 'Green Farm' },
  { id: 'nutri-day', name: 'NutriDay' },
] as const;

type ProductSeed = [
  string,
  string,
  string,
  string,
  number,
  string,
  string,
  DietaryTag[],
  ProductStockStatus,
  number,
  number,
  boolean,
  number?,
];

const seeds: ProductSeed[] = [
  [
    'oat-milk-original',
    'Sữa yến mạch nguyên bản',
    'plant-milk',
    'healthyhub-select',
    69000,
    '🥛',
    'Vị thanh nhẹ, thông tin thành phần rõ ràng.',
    ['vegan', 'lactose-free'],
    'in_stock',
    4.8,
    128,
    true,
  ],
  [
    'almond-milk-unsweetened',
    'Sữa hạnh nhân không đường',
    'plant-milk',
    'moc-nhien',
    79000,
    '🥛',
    'Lựa chọn từ hạnh nhân, không bổ sung đường.',
    ['sugar-free', 'vegan', 'lactose-free'],
    'low_stock',
    4.7,
    94,
    true,
    89000,
  ],
  [
    'cashew-cocoa-milk',
    'Sữa hạt điều cacao',
    'plant-milk',
    'green-farm',
    75000,
    '🍫',
    'Hương cacao kết hợp nền sữa hạt điều.',
    ['vegetarian', 'lactose-free'],
    'in_stock',
    4.5,
    61,
    false,
  ],
  [
    'greek-yogurt-plain',
    'Sữa chua kiểu Hy Lạp nguyên vị',
    'yogurt',
    'nutri-day',
    42000,
    '🥣',
    'Kết cấu sánh, phù hợp bữa phụ tiện lợi.',
    ['high-protein', 'low-sugar', 'gluten-free'],
    'in_stock',
    4.9,
    176,
    true,
  ],
  [
    'coconut-yogurt-mango',
    'Sữa chua dừa vị xoài',
    'yogurt',
    'moc-nhien',
    39000,
    '🥭',
    'Nền dừa kết hợp vị xoài dịu nhẹ.',
    ['vegan', 'lactose-free'],
    'out_of_stock',
    4.4,
    48,
    false,
  ],
  [
    'kombucha-ginger',
    'Kombucha gừng và chanh',
    'healthy-drinks',
    'green-farm',
    45000,
    '🍋',
    'Đồ uống lên men với gừng và chanh.',
    ['vegan', 'organic'],
    'in_stock',
    4.6,
    83,
    true,
  ],
  [
    'cold-brew-coconut',
    'Cold brew nước dừa',
    'healthy-drinks',
    'healthyhub-select',
    49000,
    '🥥',
    'Cà phê ủ lạnh kết hợp nước dừa.',
    ['vegan', 'gluten-free'],
    'in_stock',
    4.3,
    57,
    false,
  ],
  [
    'chia-lemon-drink',
    'Nước chanh hạt chia',
    'healthy-drinks',
    'moc-nhien',
    35000,
    '🍋',
    'Thức uống tiện lợi với hạt chia.',
    ['vegetarian', 'low-sugar'],
    'low_stock',
    4.2,
    39,
    false,
  ],
  [
    'berry-granola',
    'Granola hạt và quả mọng',
    'whole-grains',
    'healthyhub-select',
    119000,
    '🥣',
    'Yến mạch, các loại hạt và quả mọng sấy.',
    ['vegetarian', 'high-protein'],
    'in_stock',
    4.9,
    211,
    true,
    139000,
  ],
  [
    'cocoa-granola',
    'Granola cacao ít đường',
    'whole-grains',
    'nutri-day',
    109000,
    '🍫',
    'Granola cacao có vị ngọt vừa phải.',
    ['low-sugar', 'vegetarian'],
    'in_stock',
    4.6,
    107,
    false,
  ],
  [
    'overnight-oats-apple',
    'Yến mạch ngâm táo quế',
    'whole-grains',
    'green-farm',
    62000,
    '🍎',
    'Bữa sáng yến mạch gọn nhẹ với táo quế.',
    ['vegetarian', 'high-protein'],
    'low_stock',
    4.5,
    73,
    false,
  ],
  [
    'mixed-nuts',
    'Hạt dinh dưỡng phối trộn',
    'healthy-snacks',
    'healthyhub-select',
    89000,
    '🥜',
    'Hỗn hợp hạt rang không tẩm vị đậm.',
    ['vegan', 'gluten-free'],
    'in_stock',
    4.8,
    194,
    true,
  ],
  [
    'seaweed-chips',
    'Snack rong biển giòn',
    'healthy-snacks',
    'moc-nhien',
    32000,
    '🌿',
    'Rong biển giòn dùng cho bữa phụ.',
    ['vegan', 'gluten-free'],
    'in_stock',
    4.1,
    42,
    false,
  ],
  [
    'chickpea-bites',
    'Bánh giòn đậu gà',
    'healthy-snacks',
    'nutri-day',
    48000,
    '🫘',
    'Bánh giòn từ đậu gà, đóng gói tiện lợi.',
    ['vegan', 'high-protein'],
    'out_of_stock',
    4.4,
    66,
    false,
  ],
  [
    'quinoa-salad',
    'Salad quinoa rau củ',
    'ready-meals',
    'green-farm',
    85000,
    '🥗',
    'Quinoa và rau củ theo khẩu phần tiện lợi.',
    ['vegan', 'gluten-free'],
    'in_stock',
    4.7,
    92,
    true,
  ],
  [
    'chicken-grain-bowl',
    'Bowl gà và ngũ cốc nguyên hạt',
    'ready-meals',
    'healthyhub-select',
    99000,
    '🍲',
    'Bữa ăn gồm gà, rau và ngũ cốc.',
    ['high-protein'],
    'low_stock',
    4.8,
    135,
    true,
  ],
  [
    'tofu-soba-bowl',
    'Bowl đậu hũ và mì soba',
    'ready-meals',
    'moc-nhien',
    89000,
    '🍜',
    'Đậu hũ, rau củ và mì soba.',
    ['vegetarian', 'high-protein'],
    'in_stock',
    4.5,
    78,
    false,
  ],
  [
    'protein-bar-peanut',
    'Thanh protein bơ đậu phộng',
    'high-protein',
    'nutri-day',
    45000,
    '🍫',
    'Thanh ăn nhẹ giàu protein vị bơ đậu phộng.',
    ['high-protein', 'low-sugar'],
    'in_stock',
    4.6,
    154,
    true,
  ],
  [
    'soy-protein-cookie',
    'Bánh quy protein đậu nành',
    'high-protein',
    'green-farm',
    52000,
    '🍪',
    'Bánh quy dùng đậu nành làm nguồn protein.',
    ['high-protein', 'vegetarian'],
    'in_stock',
    4.3,
    51,
    false,
  ],
  [
    'chia-pudding-mango',
    'Chia pudding vị xoài',
    'low-sugar',
    'healthyhub-select',
    55000,
    '🥭',
    'Pudding hạt chia với xoài theo khẩu phần.',
    ['low-sugar', 'vegetarian', 'gluten-free'],
    'in_stock',
    4.7,
    118,
    true,
  ],
  [
    'coconut-crackers',
    'Bánh giòn dừa không đường',
    'low-sugar',
    'moc-nhien',
    59000,
    '🥥',
    'Bánh giòn vị dừa không bổ sung đường.',
    ['sugar-free', 'vegan'],
    'low_stock',
    4.2,
    44,
    false,
  ],
  [
    'organic-oat-cup',
    'Cốc yến mạch hữu cơ',
    'whole-grains',
    'green-farm',
    58000,
    '🌾',
    'Yến mạch dạng cốc, thuận tiện chuẩn bị.',
    ['organic', 'vegan'],
    'in_stock',
    4.5,
    69,
    false,
  ],
  [
    'vegan-protein-bowl',
    'Bowl protein thực vật',
    'high-protein',
    'healthyhub-select',
    105000,
    '🥗',
    'Đậu, quinoa và rau củ trong một khẩu phần.',
    ['vegan', 'high-protein', 'gluten-free'],
    'in_stock',
    4.9,
    163,
    true,
  ],
  [
    'plain-nut-yogurt',
    'Sữa chua hạt nguyên vị',
    'yogurt',
    'moc-nhien',
    44000,
    '🥣',
    'Sữa chua nền hạt với vị nguyên bản.',
    ['vegan', 'lactose-free', 'low-sugar'],
    'in_stock',
    4.6,
    88,
    false,
  ],
];

const productDetailData: Record<
  string,
  Pick<
    ProductPresentationModel,
    | 'nutrition'
    | 'ingredients'
    | 'allergenInformation'
    | 'storageNote'
    | 'usageNote'
    | 'longDescription'
  > & { galleryLabels?: string[] }
> = {
  'oat-milk-original': {
    galleryLabels: ['Mặt trước', 'Thông tin thành phần', 'Gợi ý dùng'],
    nutrition: {
      servingSize: '250 ml',
      calories: '120 kcal',
      protein: '3 g',
      carbohydrates: '18 g',
      fat: '4 g',
      sugar: '6 g',
      note: 'Thông tin trình bày theo một khẩu phần; cần đối chiếu nhãn sản phẩm khi nguồn media/API chính thức được tích hợp.',
    },
    ingredients: [
      { name: 'Nước' },
      { name: 'Yến mạch', description: 'Thành phần nền của sản phẩm presentation.' },
      { name: 'Dầu thực vật' },
      { name: 'Muối' },
    ],
    allergenInformation:
      'Có chứa yến mạch. Thông tin dị ứng chính thức cần đối chiếu trên nhãn sản phẩm.',
    storageNote:
      'Bảo quản nơi khô ráo; sau khi mở nắp, bảo quản lạnh và dùng theo hướng dẫn trên bao bì.',
    usageNote: 'Lắc đều trước khi dùng. Có thể dùng trực tiếp hoặc kết hợp cùng ngũ cốc.',
    longDescription:
      'Sữa yến mạch nguyên bản là lựa chọn đồ uống từ thực vật với vị thanh nhẹ. Nội dung V1 giúp trình bày cấu trúc Product Detail và sẽ được thay bằng dữ liệu public đã duyệt khi Product API sẵn sàng.',
  },
  'almond-milk-unsweetened': {
    galleryLabels: ['Mặt trước', 'Thông tin sản phẩm'],
    nutrition: {
      servingSize: '250 ml',
      calories: '70 kcal',
      protein: '2 g',
      carbohydrates: '5 g',
      fat: '4 g',
      sugar: '0 g',
    },
    ingredients: [{ name: 'Nước' }, { name: 'Hạnh nhân' }],
    allergenInformation: 'Có chứa hạnh nhân.',
    storageNote: 'Bảo quản theo hướng dẫn trên bao bì sản phẩm.',
    usageNote: 'Lắc đều trước khi dùng.',
    longDescription:
      'Đồ uống hạnh nhân không bổ sung đường, được trình bày với thông tin thành phần và tình trạng hàng rõ ràng.',
  },
  'coconut-yogurt-mango': {
    galleryLabels: ['Mặt trước'],
    nutrition: undefined,
    ingredients: [{ name: 'Nền dừa' }, { name: 'Xoài' }],
    allergenInformation: undefined,
    storageNote: 'Bảo quản lạnh theo hướng dẫn trên bao bì.',
    usageNote: undefined,
    longDescription:
      'Sữa chua nền dừa kết hợp vị xoài. Sản phẩm presentation hiện được đánh dấu hết hàng.',
  },
};

export const catalogProducts: ProductPresentationModel[] = seeds.map((seed, index) => {
  const [
    slug,
    name,
    categoryId,
    brandId,
    price,
    visualFallback,
    shortDescription,
    dietaryTags,
    stockStatus,
    rating,
    reviewCount,
    featured,
    originalPrice,
  ] = seed;
  const category = productCategories.find((item) => item.id === categoryId)!;
  const brand = productBrands.find((item) => item.id === brandId)!;
  const discountPercent = originalPrice ? Math.round((1 - price / originalPrice) * 100) : undefined;
  const detail = productDetailData[slug];
  const galleryLabels = detail?.galleryLabels ?? ['Hình minh họa'];
  return {
    id: String(index + 1),
    slug,
    sku: `HH-${String(index + 1).padStart(4, '0')}`,
    name,
    shortDescription,
    category: { ...category },
    brand: { ...brand },
    images: galleryLabels.map((label, mediaIndex) => ({
      id: `${slug}-media-${mediaIndex + 1}`,
      src: null,
      alt: `${label} của ${name}`,
      label,
      visualFallback,
    })),
    thumbnail: null,
    visualFallback,
    price,
    originalPrice,
    discountPercent,
    rating,
    reviewCount,
    soldCount: reviewCount * 3 + index * 7,
    stockStatus,
    featured,
    badges: featured ? ['Nổi bật'] : discountPercent ? [`Giảm ${discountPercent}%`] : [],
    dietaryTags,
    nutrition: detail?.nutrition,
    ingredients: detail?.ingredients ?? [],
    allergenInformation: detail?.allergenInformation,
    storageNote: detail?.storageNote,
    usageNote: detail?.usageNote,
    longDescription: detail?.longDescription,
    createdAt: new Date(Date.UTC(2026, 6, 24 - index)).toISOString(),
  };
});
